{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 1,
      "Layer": "0",
      "LinePoints": [
        {
          "Point": 1,
          "X": 1837.25,
          "Y": 1879.95
        },
        {
          "Point": 2,
          "X": 2021.01,
          "Y": 1684.04
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 2,
      "Layer": "0",
      "LinePoints": [
        {
          "Point": 1,
          "X": 2070.02,
          "Y": 1772.81
        },
        {
          "Point": 2,
          "X": 2281.35,
          "Y": 1907.5
        }
      ]
    }
  ]
}