{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 1,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 1377.8364422390041,
          "Y": 1956.4799584277989
        },
        {
          "Point": 2,
          "X": 1423.7777101388838,
          "Y": 1411.6035898177515
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 2,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 1742.3037779827318,
          "Y": 1907.5023038208528
        },
        {
          "Point": 2,
          "X": 1742.3037779827318,
          "Y": 1289.1594597824242
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Polyline",
      "Internal_Id": 3,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 2198.6536495262226,
          "Y": 1931.9911311243259
        },
        {
          "Point": 2,
          "X": 2198.6536495262226,
          "Y": 1313.6482870858972
        },
        {
          "Point": 3,
          "X": 2753.0115287411463,
          "Y": 1371.8092454496082
        },
        {
          "Point": 4,
          "X": 2753.0115287411463,
          "Y": 1693.2250843615775
        },
        {
          "Point": 5,
          "X": 2198.6536495262226,
          "Y": 1931.9911311243259
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Polyline",
      "Internal_Id": 4,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 2106.7711280303574,
          "Y": 2394.21771406719
        },
        {
          "Point": 2,
          "X": 2106.7711280303574,
          "Y": 2121.779529762166
        },
        {
          "Point": 3,
          "X": 2615.1877536492957,
          "Y": 2121.779529762166
        },
        {
          "Point": 4,
          "X": 2691.7565096426042,
          "Y": 2311.5679284000062
        },
        {
          "Point": 5,
          "X": 3255.3026538806207,
          "Y": 2183.0015915388112
        },
        {
          "Point": 6,
          "X": 3255.3026538806207,
          "Y": 1827.913621566604
        },
        {
          "Point": 7,
          "X": 3653.4602565653004,
          "Y": 1472.8256515943967
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Circle",
      "Internal_Id": 5,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 3022.5335927492761,
          "Y": 1237.1207082445826
        }
      ],
      "Radius": 254.19007622454217
    }
  ]
}