{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 3,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 1736.178277503268,
          "Y": 1436.0924171212246
        },
        {
          "Point": 2,
          "X": 2236.178277503268,
          "Y": 1436.0924171212246
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 5,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 1736.178277503268,
          "Y": 1436.0924171212246
        },
        {
          "Point": 2,
          "X": 2236.178277503268,
          "Y": 1436.0924171212246
        }
      ]
    }
  ],
  "Dimensions": [
    {
      "XDimPoints": [
        {
          "Dim Point": 1,
          "DimX": 1736.178277503268,
          "DimY": 1436.0924171212246
        },
        {
          "Dim Point": 2,
          "DimX": 2236.178277503268,
          "DimY": 1436.0924171212246
        },
        {
          "Dim Point": 3,
          "DimX": 2236.178277503268,
          "DimY": 1501.286917919595
        }
      ],
      "Internal_Id": 4,
      "Dimension Style": "(2336083573360)",
      "Dimension Style Name": "ISO-25",
      "Layer": "0",
      "Dim rotation": 0.0
    },
    {
      "XDimPoints": [
        {
          "Dim Point": 1,
          "DimX": 1736.178277503268,
          "DimY": 1436.0924171212246
        },
        {
          "Dim Point": 2,
          "DimX": 2236.178277503268,
          "DimY": 1436.0924171212246
        },
        {
          "Dim Point": 3,
          "DimX": 2236.178277503268,
          "DimY": 1501.286917919595
        }
      ],
      "Internal_Id": 6,
      "Dimension Style": "(2336083573360)",
      "Dimension Style Name": "ISO-25",
      "Layer": "0",
      "Dim rotation": 0.0
    }
  ]
}