{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Polyline",
      "Internal_Id": 1,
      "Layer": "0",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 2140.4613806674115,
          "Y": 1567.7198509133168
        },
        {
          "Point": 2,
          "X": 2140.4613806674115,
          "Y": 1001.4157584127306
        },
        {
          "Point": 3,
          "X": 2688.6937594028714,
          "Y": 1001.4157584127306
        },
        {
          "Point": 4,
          "X": 2688.6937594028714,
          "Y": 1576.9031611521186
        },
        {
          "Point": 5,
          "X": 2140.4613806674115,
          "Y": 1567.7198509133168
        }
      ]
    }
  ]
}