{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 1,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": -560.0,
          "Y": 12560.0
        },
        {
          "Point": 2,
          "X": 5560.0,
          "Y": 12560.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 2,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 0.0,
          "Y": 12000.0
        },
        {
          "Point": 2,
          "X": 5000.0,
          "Y": 12000.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 3,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 5560.0,
          "Y": -560.0
        },
        {
          "Point": 2,
          "X": 5560.0,
          "Y": 12560.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 4,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 5000.0,
          "Y": 0.0
        },
        {
          "Point": 2,
          "X": 5000.0,
          "Y": 12000.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 5,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": -560.0,
          "Y": -560.0
        },
        {
          "Point": 2,
          "X": -560.0,
          "Y": 12560.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 6,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 0.0,
          "Y": 0.0
        },
        {
          "Point": 2,
          "X": 0.0,
          "Y": 12000.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 7,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": -560.0,
          "Y": -560.0
        },
        {
          "Point": 2,
          "X": 5560.0,
          "Y": -560.0
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 8,
      "Layer": "equipment",
      "LineOrCenterPoints": [
        {
          "Point": 1,
          "X": 0.0,
          "Y": 0.0
        },
        {
          "Point": 2,
          "X": 5000.0,
          "Y": 0.0
        }
      ]
    }
  ]
}