{
  "Blocks": [],
  "Lines": [
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 1,
      "Layer": "0",
      "LinePoints": [
        {
          "Point": 1,
          "X": 1733.12,
          "Y": 1999.34
        },
        {
          "Point": 2,
          "X": 1996.51,
          "Y": 1515.68
        }
      ]
    },
    {
      "Type": "Autodesk.AutoCAD.DatabaseServices.Line",
      "Internal_Id": 2,
      "Layer": "0",
      "LinePoints": [
        {
          "Point": 1,
          "X": 2192.53,
          "Y": 1356.5
        },
        {
          "Point": 2,
          "X": 2471.24,
          "Y": 1913.62
        }
      ]
    }
  ]
}